---
- name: install common command line tools
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - dos2unix
    - glances
    - grc
    - htop
    - mtr
    - multitail
    - silversearcher-ag
    - tree
    - wget
